---
include:
  - board: nice_nano@2.0.0//zmk
    shield: eyelash_sofle_central_dongle dongle_display
    artifact-name: eyelash_sofle_central_dongle_oled
  - board: nice_nano@2.0.0//zmk
    shield: eyelash_sofle_peripheral_left nice_view
  - board: nice_nano@2.0.0//zmk
    shield: eyelash_sofle_peripheral_right nice_view
  - board: nice_nano@2.0.0//zmk
    shield: settings_reset
